url: "https://www.jingyazh.com"  
baseurl: ""
permalink: pretty

plugins:
  - jekyll-paginate
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
    values:
      permalink: pretty
      include: ['.htaccess'] 


<a href="{{ 'index' | permalink }}">Home</a>
